#!/bin/bash
# shellcheck disable=SC1090
[ -f /.dockerenv ] || { echo "please run in supplied container"; exit 1; }
set -e; eval "$(environment)"

external_dir="${EXTERNAL_DIR?}"
device="${DEVICE?}"
kernel_dir="${external_dir}/kernel/${device}"
cores=$(nproc)

# This seems like it -should- work but the AOSP kernel build system
# seems to ignore it and generate new keys anyway
# It is better for determinism and security to disable loadable module support
# anyway, which some patchsets choose to do.
#ln -vs \
#	"${key_dir}/kernel.pem" \
#	"${kernel_dir}/private/msm-google/certs/signing_key.pem"
cd "${kernel_dir}"
cat <<-EOF | bash
	export OUT_DIR="${kernel_dir}/out"
	export DIST_DIR="${kernel_dir}/dist"
	bash "${kernel_dir}/build/build.sh" -j "${cores}"
EOF
