#!/bin/bash
[ -f /.dockerenv ] || { echo "please run in supplied container"; exit 1; }
set -e; eval "$(environment)"

external_dir="${EXTERNAL_DIR?}"
base_dir="${BASE_DIR?}"

[ -d "$base_dir" ] && {
	cd "$base_dir"
	[ -f ".repo/manifests/.git/HEAD" ] && {
		repo --no-pager forall --abort-on-errors -p --verbose -c 'git reset --hard ; git clean --force -dx';
	}
	[ -f "Makefile" ] && make clean
	[ -d "${external_dir}/kernel" ] && {
		mapfile -t -d '' dirs \
			< <(find "${external_dir}/kernel" -maxdepth 1 -mindepth 1 -type d -print0)
		for dir in "${dirs[@]}"; do (
			[ -f "$dir/.repo/manifests/.git/HEAD" ] && {
				cat <<-EOF | bash
					cd "$dir" || exit;
					repo --no-pager forall --abort-on-errors -p --verbose -c 'git reset --hard ; git clean --force -dx';
					rm -rf dist
				EOF
			}
		) done
	}
}
