#!/bin/bash
[ -f /.dockerenv ] || { echo "please run in supplied container"; exit 1; }
set -e; eval "$(environment)"

[ -d "$HOME/base" ] && {
	cd "$HOME/base"
	[ -d ".repo/manifests/.git/HEAD" ] && {
		repo forall -c 'git reset --hard ; git clean -fdx';
	}
	[ -f "Makefile" ] && make clean
	[ -d "$HOME/external/kernel" ] && {
		mapfile -t -d '' dirs \
			< <(find "$HOME/external/kernel" -maxdepth 1 -mindepth 1 -type d -print0)
		for dir in "${dirs[@]}"; do (
			[ ! -d "$dir/.repo/manifests/.git/HEAD" ] || {
				cat <<-EOF | bash
					cd "$dir" || exit;
					repo forall -c 'git reset --hard ; git clean -fdx';
					rm -rf out
				EOF
			}
		) done
	}
}

rm -rf "$HOME"/{external/chromium/out,.gradle,.android,.cache,.repoconfig,base/.repo}
