#!/usr/bin/python3

import yaml
from os import environ, getenv, getcwd
from os.path import isfile
from time import strftime, gmtime

cwd = getcwd()
cross64 = "prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/bin"
cross32 = "prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/bin"
libfaketime = "/usr/lib/x86_64-linux-gnu/faketime/libfaketime.so.1"
if 'BASE_DIR' in environ:
    base_dir = environ['BASE_DIR']
else:
    base_dir = "{}/build/base".format(cwd)

config_file='{}/config/config.yml'.format(cwd)
with open(config_file, encoding='utf-8') as data_file:
    config = yaml.load(data_file.read())

patches = ", ".join(config.get('platform',{}).get('patches',[]))

environment = {
    "OS_NAME": config['name'],
    "CONFIG_FILE": config_file,
    "CONFIG_DIR": '{}/config'.format(cwd),
    "BASE_DIR": base_dir,
    "ANDROID_HOME": "{}/sdk".format(base_dir),
    "MANIFEST_REPO": "{}/config/manifests".format(cwd),
    "MANIFEST_DIR": "{}/config/manifests".format(cwd),
    "OVERLAY_DIR": "{}/config/overlay".format(cwd),
    "PATCH_DIR": "{}/config/patches".format(cwd),
    "EXTERNAL_DIR": "{}/build/external".format(cwd),
    "DEVICES": ",".join(config['devices'].keys()),
    "PLATFORM_PATCHES": patches,
    "BUILD_HOST": config['host'],
    "BUILD_USER": config['user'],
    "BUILD_TYPE": config['type'],
    "BUILD_VARIANT": config['variant'],
    "BUILD_NUMBER": strftime('%m%d%H%M', gmtime(config['datetime'])),
    "FAKETIME": strftime('%Y-%m-%d %H:%M:%S', gmtime(config['datetime'])),
    "BUILD_DATETIME": config['datetime'],
    "KBUILD_BUILD_TIMESTAMP":
        strftime('%Y-%m-%dT%H:%M:%SZ', gmtime(config['datetime'])),
    "KBUILD_BUILD_USER": config['user'],
    "KBUILD_BUILD_HOST": config['host'],
    "KBUILD_BUILD_VERSION": \
        strftime('%m%d%H%M', gmtime(config['datetime'])),
    "KCONFIG_NOTIMESTAMP": 1,
    "RANDFILE": "{}/build/randfile.bin".format(cwd),
    "LC_ALL":"C",
    #  "PS4": '+ $(/bin/date --rfc-3339=seconds) ',
}

environment['BUILD_KERNEL'] = "true"
if config.get('build_kernel') == False:
    environment['BUILD_KERNEL'] = "false"

if 'OTA_CHANNEL' in environ and len(environ['OTA_CHANNEL']) > 0:
    environment['OTA_CHANNEL']=environ['OTA_CHANNEL']

if 'DEVICE' in environ and len(environ['DEVICE']) > 0:
    device=environment['DEVICE']=environ['DEVICE']
    variant=environment['BUILD_VARIANT']
    build_number=environment['BUILD_NUMBER']
    device_config=config['devices'][device]
    for key, value in device_config.items():
        environment[key.upper()]=value.lower()
    if variant == "user" or variant == "userdebug":
        key_dir = "{}/keys/{}".format(cwd, device)
    else:
        key_dir = "{}/build/target/product/security/".format(base_dir)
    environment["KEY_DIR"] = key_dir
    environment["RELEASE_DIR"] = "{}/release/".format(cwd)
    environment['BUILD_ID'] = device_config['build_id']

environment['ARCH'] = "arm64"
environment['LANG'] = "C"
environment['CONFIG_COMPAT_VDSO'] = "n"
environment['CROSS_COMPILE'] = \
    '{}/{}/aarch64-linux-android-'.format(base_dir, cross64)
environment['CROSS_COMPILE_ARM32'] = \
    '{}/{}/arm-linux-androideabi-'.format(base_dir, cross32)

paths = [
    '.repo/repo',
    'prebuilts/jdk/jdk11/linux-x86/bin',
    'build/tools/releasetools',
    'development/tools',
    'external/avb',
    'out/host/linux-x86/bin',
    cross32,
    cross64,
]

envsetup = '{}/build/envsetup.sh'.format(base_dir)
if isfile(envsetup):
    print('source {}'.format(envsetup))
for path in paths:
    print('export PATH="{}/{}:$PATH"'.format(
        environment['BASE_DIR'], path
    ))
for name, value in environment.items():
    print('export {}="{}"'.format(name, value))
