#!/usr/bin/env python3

# Original Source from: https://github.com/GrapheneOS/script

from argparse import ArgumentParser
from os import path
from zipfile import ZipFile
from enum import Enum


class Channels(Enum):
    stable = "stable"
    beta = "beta"
    testing = "testing"

    def __str__(self):
        return self.value


parser = ArgumentParser(description="Generate update server metadata")
parser.add_argument("--channel", type=Channels, choices=list(Channels),
                    default=Channels.testing, help="The channel the OTA should be released on.")
parser.add_argument("zip")

zip_path = parser.parse_args().zip
channel = parser.parse_args().channel

with ZipFile(zip_path) as f:
    with f.open("META-INF/com/android/metadata") as metadata:
        data = dict(line[:-1].decode().split("=") for line in metadata)
        my_path = path.join(
            path.dirname(zip_path),
            data["pre-device"] + "-" + str(channel)
        )
        with open(my_path, "w") as output:
            build_id = data["post-build"].split("/")[3]
            incremental = data["post-build"].split("/")[4].split(":")[0]
            print(incremental, data["post-timestamp"], build_id, file=output)
