#!/usr/bin/python3

from tempfile import mkdtemp
from git import Git, Repo, cmd
import git
from xml.etree import ElementTree
from xml.etree.ElementTree import Element
from xml.dom import minidom
from sys import argv, exit
from os import environ, getcwd, getenv, makedirs
from os.path import isfile, isdir
import re
import time
import yaml

class AndroidManifest:

    def __init__(
        self,
        ref,
        name,
        repo='platform/manifest',
        extra_remotes=[],
        extra_projects=[],
        remove_paths=[],
        remove_groups=[]
    ):
        self.default_fetch="https://android.googlesource.com"
        self.ref = ref
        self.name = name
        self.repo = repo
        self.extra_remotes = extra_remotes
        self.extra_projects = extra_projects
        self.remove_paths = remove_paths
        self.remove_groups = frozenset(remove_groups)
        for project in self.extra_projects:
            self.remove_paths.append(project['path'])
        self._fetch()
        self._remove()
        self._extend()
        self._set_default_revision()
        self._set_remotes()
        self._set_default_remote()
        self._lock()

    def _fetch(self):
        manifest_url = "%s/%s" % (self.default_fetch, self.repo)
        print("[{}] Checking out: \"{}\" at \"{}\"".format(
            self.name,
            manifest_url,
            self.ref
        ))
        manifest_repo = Repo.clone_from(manifest_url, mkdtemp(), branch=self.ref, depth=1)
        string = manifest_repo.git.show('HEAD:default.xml')
        self.manifest = ElementTree.fromstring(string)

    def _extend(self):
        for remote in self.extra_remotes:
            element = Element("remote")
            element.attrib = remote
            element.tail = "\n"
            self.manifest.insert(1,element)
            print("[{}] Adding Remote: \"{}\"".format(
                self.name,
                element.attrib['name']
            ))
        for project in self.extra_projects:
            element = Element("project")
            element.text = "\n"
            if 'children' in project:
                children = project.pop('children', None)
                for child in children:
                    if 'tag' in child:
                        tag = child.pop('tag', None)
                    subelement = Element(tag)
                    subelement.attrib = child
                    subelement.tail = "\n"
                    element.append(subelement)
            element.attrib = project
            element.tail = "\n"
            self.manifest.insert(4,element)
            print("[{}] Adding Project: \"{}\"".format(
                self.name,
                element.attrib['name']
            ))

    def _remove(self):
        for project in self.manifest.findall(".//project"):
            path=project.attrib['path']
            if 'groups' in project.attrib:
                groups_string = project.attrib['groups']

                ## from `repo` program source: manifest_xml.py
                groups = [x for x in re.split(r'[,\s]+', groups_string) if x]

                group_intersections = self.remove_groups.intersection(groups)
                if len(group_intersections):
                    print("[{}] Removing Project: \"{}\" (because of remove_groups {})".format(
                        self.name,
                        path,
                        list(group_intersections),
                    ))
                    self.manifest.remove(project)
        for project in self.manifest.findall(".//project"):
            path=project.attrib['path']
            if 'path' in project.attrib:
                if project.attrib['path'] in self.remove_paths:
                    print("[{}] Removing Project: \"{}\"".format(
                        self.name,
                        path
                    ))
                    self.manifest.remove(project)

    def _set_remotes(self):
        self.remotes={}
        remote_nodes = self.manifest.findall(".//remote")
        for remote_node in remote_nodes:
            self.remotes[remote_node.attrib["name"]] = {}
            if 'fetch' in remote_node.attrib:
                if remote_node.attrib['fetch'] == '..':
                    remote_node.attrib['fetch'] = self.default_fetch
            else:
                remote_node.attrib['fetch'] = self.default_fetch
            self.remotes[remote_node.attrib["name"]]['fetch'] = \
                remote_node.attrib['fetch']
            if 'review' in remote_node.attrib:
                self.remotes[remote_node.attrib["name"]]['review'] = \
                    remote_node.attrib["review"]
            if 'revision' in remote_node.attrib:
                self.remotes[remote_node.attrib["name"]]["revision"] = \
                    remote_node.attrib["revision"]
            else:
                self.remotes[remote_node.attrib["name"]]["revision"] = \
                    self.default_revision
            print("[{}] Adding Remote: \"{}\"".format(
                self.name,
                remote_node.attrib['name'],
            ))

    def _set_default_revision(self):
        self.default_revision = \
            revision=self.manifest.findall(".//default")[0].attrib['revision']
        print("[{}] Setting Revision: \"{}\"".format(self.name, revision))

    def _set_default_remote(self):
        default_remote_name = \
            self.manifest.findall(".//default")[0].attrib['remote']
        self.default_remote = default_remote_name
        print("[{}] Setting Default Remote: \"{}\"".format(
            self.name,
            default_remote_name
        ))

    def _lock(self):
        projects=self.manifest.findall(".//project")
        for project in projects:
            print("[{}] Locking Project: \"{}\" (path \"{}\")".format(
                self.name,
                project.attrib['name'],
                project.attrib['path'],
            ))
            if 'remote' in project.attrib:
                remote = self.remotes[project.attrib['remote']]
            else:
                remote = self.remotes[self.default_remote]
            if 'revision' in project.attrib:
                revision = project.attrib['revision']
            elif 'revision' in remote:
                revision = remote['revision']
            if 'refs' not in revision:
                revision = "refs/heads/%s" % revision
            project_repo_url="%s/%s.git" % (
                remote.get('fetch', self.remotes[self.default_remote]['fetch']),
                project.attrib['name']
            )
            project.attrib['upstream'] = revision
            project.attrib['revision'] = self._lsremote(project_repo_url, revision)

    def _lsremote(self, url, refs):
        remote_refs = {}
        g = cmd.Git()
        for x in range(5):
            try:
                return g.ls_remote(url, refs).split('\t')[0]
            except git.exc.GitCommandError:
                print("Caught GitCommandError exception for the {} time. Retrying.".format(x))
                time.sleep(2**x)
        raise Exception("Repeatedly failed trying git ls-remote.")

    def pretty_print(self):
        rough_string = ElementTree.tostring(self.manifest, 'utf-8')
        reparsed = minidom.parseString(rough_string)
        return reparsed.toprettyxml(indent="  ", newl="")

if __name__ == "__main__":

    config_file=getenv('CONFIG_FILE')
    print("Config file: %s" % config_file)
    with open(config_file, encoding='utf-8') as data_file:
        config = yaml.load(data_file.read())

    path=getenv('MANIFEST_DIR')

    kernel_names=[]
    manifest_kernels=[]
    devices=config['devices'].keys()
    if 'DEVICE' in environ and len(environ['DEVICE']) > 0:
        devices=[environ['DEVICE']]

    for device in devices:
        makedirs('{}/{}'.format(path, device), exist_ok=True)
        filename = '{}/{}/kernel.xml'.format(path, device)
        kernel_manifest = AndroidManifest(
            name="{}-kernel".format(device),
            ref=config['devices'][device]['kernel_ref'],
            repo="kernel/manifest",
        ).pretty_print()
        open(filename,'w').write(kernel_manifest)

        base_manifest = AndroidManifest(
            ref=config['devices'][device]['platform_ref'],
            name="{}-base".format(device),
            extra_remotes = config.get('platform',{}).get('extra_remotes',[]),
            extra_projects = config.get('platform',{}).get('extra_projects',[]),
            remove_paths = config.get('platform',{}).get('remove_paths',[]),
            remove_groups = config.get('platform',{}).get('remove_groups',[]),
        ).pretty_print()
        open('{}/{}/base.xml'.format(path,device),'w').write(base_manifest)

    repo = Repo.init(path)
    repo.index.add(['*'])
    repo.index.commit("manifest commit")
