#!/bin/bash
# shellcheck disable=SC1091,SC1090
[ -f /.dockerenv ] || { echo "please run in supplied container"; exit 1; }
set -e; eval "$(environment)"

img_path() {
	image=${1?}
	path=${2?}
 	grep -Po \
 		"require version-${image}=\\K.+" \
 		"${path}/vendor-board-info.txt" \
 	| tr '[:upper:]' '[:lower:]'
}

device="${DEVICE?}"
base_dir="${BASE_DIR?}"
build_number="${BUILD_NUMBER?}"
build_datetime="${BUILD_DATETIME?}"
key_dir="${KEY_DIR?}"
device_key_dir="${key_dir?}/device/${device}"
apex_key_dir="${key_dir?}/apex"
release_dir="${RELEASE_DIR?}"
build_id=${BUILD_ID?}

prefix=aosp_
target_files="${device}-target_files-${build_number}.zip"
target_out_dir="${base_dir}/out/target/product/${device}"
inter_dir="${target_out_dir}/obj/PACKAGING/target_files_intermediates"
bootloader=$(img_path bootloader "${base_dir}/vendor/google_devices/${device}")
radio=$(img_path baseband "${base_dir}/vendor/google_devices/${device}")

sudo chown -R "$(id -u)":"$(id -g)" "$HOME/release"

cd "$base_dir"
mkdir -p "$release_dir"

echo "Running sign_target_files_apks"
sign_target_files_apks \
	--default_key_mappings "$device_key_dir" \
	--avb_vbmeta_key "${device_key_dir}/avb.pem" \
	--avb_vbmeta_algorithm SHA256_RSA2048 \
	--avb_system_key "${device_key_dir}/avb.pem" \
	--avb_system_algorithm SHA256_RSA2048 \
	--avb_system_key "${device_key_dir}/avb.pem" \
	--key_mapping \
		"build/target/product/security/networkstack=${device_key_dir}/networkstack" \
	--extra_apks \
		"com.android.conscrypt.apex=${apex_key_dir}/com.android.conscrypt" \
    --extra_apex_payload_key \
    	"com.android.conscrypt.apex=${apex_key_dir}/com.android.conscrypt.pem" \
	--extra_apks \
		"com.android.media.apex=${apex_key_dir}/com.android.media" \
    --extra_apex_payload_key \
    	"com.android.media.apex=${apex_key_dir}/com.android.media.pem" \
	--extra_apks \
		"com.android.media.swcodec.apex=${apex_key_dir}/com.android.media.swcodec" \
    --extra_apex_payload_key \
    	"com.android.media.swcodec.apex=${apex_key_dir}/com.android.media.swcodec.pem" \
	--extra_apks \
		"com.android.resolv.apex=${apex_key_dir}/com.android.resolv" \
    --extra_apex_payload_key \
    	"com.android.resolv.apex=${apex_key_dir}/com.android.resolv.pem" \
	--extra_apks \
		"com.android.runtime.apex=${apex_key_dir}/com.android.runtime" \
    --extra_apex_payload_key \
    	"com.android.runtime.apex=${apex_key_dir}/com.android.runtime.pem" \
	--extra_apks \
		"com.android.tzdata.apex=${apex_key_dir}/com.android.tzdata" \
    --extra_apex_payload_key \
    	"com.android.tzdata.apex=${apex_key_dir}/com.android.tzdata.pem" \
	--replace_ota_keys \
  		"${inter_dir}/${prefix}${device}-target_files-${build_number}.zip" \
	"$release_dir/$target_files"

echo "Running ota_from_target_files"
ota_from_target_files \
	--block \
	-k "${device_key_dir}/releasekey" \
  	"${release_dir}/${target_files}" \
	"${release_dir}/${device}-ota_update-${build_number}.zip"

echo 'Generating testing OTA metadata'
ota_channel=${OTA_CHANNEL:-beta}
generate-metadata \
  --channel "${ota_channel}" \
  "${release_dir}/${device}-ota_update-${build_number}.zip"

echo "Running img_from_target_files"
img_from_target_files \
	"${release_dir}/${target_files}" \
	"${release_dir}/${device}-img-${build_number}.zip"

echo "Running generate-factory-images"
cat <<-EOF | bash
	cd "$release_dir"
	source "${base_dir}/device/common/clear-factory-images-variables.sh"
	export BUILD="$build_number"
	export DEVICE="$device"
	export PRODUCT="$device"
	export VERSION="$build_id"
	export BOOTLOADER="$bootloader"
	export RADIO="$radio"
	source "${base_dir}/device/common/generate-factory-images-common.sh"
EOF

echo "Copy scripts and the avb key into factory zip"
cd "${release_dir}"
factory_zip="$(ls -t "${device}"-"${build_id}"-factory-*.zip | head -1)"
factory_tmp="${device}-${build_id}-factory.zip"
factory_dir="${device}-${build_id}"
unzip "${factory_zip}"
rm "${factory_zip}"
rm "${factory_dir}/flash-all.sh"
rm "${factory_dir}/flash-all.bat"
rm "${factory_dir}/flash-base.sh"

cat <<-EOF >> "${factory_dir}/flash-all.sh"
if ! [ \$(\$(which fastboot) --version | grep "version" | cut -c18-23 | sed 's/\.//g' ) -ge 2802 ]; then
  echo "fastboot too old; please download the latest version at https://developer.android.com/studio/releases/platform-tools.html"
  exit 1
fi

fastboot flashing unlock
fastboot flash bootloader bootloader-${device}-${bootloader}.img
fastboot reboot-bootloader
sleep 5
fastboot flash radio radio-${device}-${radio}.img
fastboot reboot-bootloader
sleep 5
fastboot erase avb_custom_key
fastboot flash avb_custom_key ${device}-avb_pkmd.bin
fastboot reboot-bootloader
sleep 5
fastboot -w --skip-reboot update image-${device}-${build_id}.zip
fastboot reboot-bootloader
sleep 5
fastboot flashing lock
EOF
chmod +x "${factory_dir}/flash-all.sh"

cp "${device_key_dir}/avb_pkmd.bin" "${factory_dir}/${device}-avb_pkmd.bin"

timestamp=$(date -d "@$build_datetime" "+%y%m%d%H%M.%S")
find "${factory_dir}" -exec touch -t "$timestamp" {} +
zip -X -r "${factory_tmp}" "${factory_dir}"
rm -rf "${factory_dir}"
factory_hash="$(sha256sum "${factory_tmp}" | cut -b -8)"
mv "${factory_tmp}" "${device}-${build_id}-factory-${factory_hash}.zip"
