#!/bin/bash
# SPDX-FileCopyrightText: 2022 Samuel Cochran <sj26@sj26.com>
#
# SPDX-License-Identifier: MIT
#
# https://gist.github.com/sj26/88e1c6584397bb7c13bd11108a579746

set -o nounset -o pipefail -o errexit

[[ $# -le 1 ]] && { echo "Usage $0 <retry_number> <command>"; }

retries="${1:-}"
shift

count=0
until "$@"; do
    exit=$?
    wait=$((2 ** count))
    count=$((count + 1))
    if [ "$count" -lt "$retries" ]; then
        echo "Try $count/$retries terminated with exit code $exit, retrying in $wait seconds ..."
        sleep $wait
    else
        echo "Try $count/$retries terminated with exit code $exit, no more retries left."
        exit $exit
    fi
done
